Ecwid/ecwid-java-api-client

build.gradle.kts

Old one is already deleted from public access

Gradle version bump 

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedCombination.kt
src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/enums/AttributeValueAlias.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/variation/result/FetchedVariation.kt

Change type from AttributeValueAlias to AttributeType
Add converter func from AttributeType to AttributeValueAlias

Change AttributeValue type field

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/coupon/request/CouponSearchRequest.kt

added DiscountCouponStatus enum to CouponSearchRequest

added DiscountCouponStatus enum to CouponSearchRequest

---

.github/workflows/gradlepublish.yml
src/test/kotlin/com/ecwid/apiclient/v3/BaseEntityTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/BatchApiTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/CartsTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/CategoriesTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/CouponsTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/CustomersTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/OrdersTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/ProductsTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/StoreProfileTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/VariationsTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/util/PropertiesLoadError.kt
src/test/kotlin/com/ecwid/apiclient/v3/util/PropertiesLoader.kt
src/test/kotlin/com/ecwid/apiclient/v3/util/TestProperties.kt

Add gradle tests on pull request

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/cart/result/FetchedCart.kt

added support for cart.acceptMarketing field

added support for cart.acceptMarketing field

---

src/main/kotlin/com/ecwid/apiclient/v3/ApiClient.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/category/request/CategoriesSearchRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/category/request/CategoryDetailsRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/ProductDetailsRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/ProductsSearchRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/profile/request/LatestStatsRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/profile/result/FetchedLatestStats.kt
src/main/kotlin/com/ecwid/apiclient/v3/impl/StoreProfileApiClientImpl.kt

Please review the changes below

Request extensions

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/ProductUpdateRequest.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NullablePropertyRules.kt

Нестыковка с документациями api https://api-docs.ecwid.com/reference/products#update-a-product

ECWID-88785 Добавил для ProductUpdateRequest checkLowStockNotificatio

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/custom/CustomAppRequest.kt

- добавил lang в CusttomAppRequest

ECWID-98199 Multilingual store: Custom Shipping API support

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/UpdatedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NullablePropertyRules.kt

- added new fields min/max in Api for degenerator

ECWID-102900 Order quantity limits for products: storefront

---

src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
src/main/kotlin/com/ecwid/apiclient/v3/httptransport/HttpRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/httptransport/impl/ConvertUtils.kt
src/main/kotlin/com/ecwid/apiclient/v3/impl/RequestInfo.kt

I propose to add requestId in params. Could you please check it?

Added requestId to API client.

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/profile/result/FetchedStoreProfile.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/StoreProfileTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NonUpdatablePropertyRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedStoreProfileRules.kt

Added new data to FetchedStroeProfile. Added subdomain suffix.

ECWID-103821 added new field FetchedStoreProfile.InstantSiteInfo.ecwidSubdomainSuffix

---

src/main/kotlin/com/ecwid/apiclient/v3/metric/RequestSizeMetric.kt
src/main/kotlin/com/ecwid/apiclient/v3/metric/RequestTimeMetric.kt
src/main/kotlin/com/ecwid/apiclient/v3/metric/ResponseSizeMetric.kt

Replace `endpoint` label with `path`

Improve prometheus metrics

---

build.gradle.kts
src/main/kotlin/com/ecwid/apiclient/v3/responsefields/ResponseFieldsBuilder.kt
src/main/kotlin/com/ecwid/apiclient/v3/responsefields/ResponseFieldsDsl.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/StoreProfileTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/responsefields/ResponseFieldsDslUnitTest.kt

Add support for prepared fields in responseFields DSL and upgrade Kotlin version

Upgrade kotlin 1.8.21 and some improvements responseFields dsl

---

.github/workflows/pull-request.yml
.github/workflows/push-to-master.yml

* Add gradle cache
* Use default concurrency
* Replace Adopt JDK for Amazon Corretto

Improve build

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/cart/request/OrderForCalculate.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/OrderForCalculateRules.kt

Added needCalculateWholesalePrice field, which enables calculating wholesale price in order item.

ECWID-124671 OE2: Send Order Data to Calculation and Display Changes: Bulk Discount Pricing.

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/order/result/FetchedOrder.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NonUpdatablePropertyRules.kt

rename shippingLabelAvailableForPurchase -> shippingLabelAvailableForShipment

ECWID-127291 Shipping labels: edit API showing availability of shipping label in the Public API v3.

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/ReportType.kt

- added conversions ReportType

ECWID-128968 New Reports: internal API for conversions report:

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/ReportType.kt

- added addToCartConversion ReportType

ECWID-129661 New Reports: internal API for addToCartConversion report

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/cart/request/OrderForCalculate.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/cart/result/CalculateOrderDetailsResult.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/cart/result/FetchedCart.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/CartsTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/CalculateOrderDetailsResultRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedCartRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/OrderForCalculateRules.kt

added taxType into OrderItemTax

ECWID-128353 OE2: Displaying USA Taxes after order recalculation:

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/ReportType.kt

- added checkoutSalesFunnel report type

ECWID-133119 New Reports: internal API for checkoutSalesFunnel report:

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/ProductUpdateRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/variation/request/UpdateProductVariationRequest.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NullablePropertyRules.kt

Функционал не понадобился. На стороне апигейта поддержка нового параметра не реализована. Выпиливаю из клиента.

Ecwid 132977 revert

---

src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/ReportType.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/report/result/FetchedReportResponse.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NullablePropertyRules.kt

ECWID-136271 New reports: internal API for abandonedCarts report

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/report/request/ReportRequest.kt

Use new parameters in toParams()

ECWID-136750 New reports: internal API for inventoryReport: Error about missing parameters

---

src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/report/result/FetchedReportResponse.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NullablePropertyRules.kt

ECWID-138042 New reports: internal API for topOfLandingPagesByVisitors report:

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/cart/result/CalculateOrderDetailsResult.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/CustomersTest.kt

fix type of declaredValue because in all another places it has Double type

ECWID-138355 fix declaredValue type

---

src/main/kotlin/com/ecwid/apiclient/v3/OrdersApiClient.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/order/request/LastOrderDetailsRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/impl/OrdersApiClientImpl.kt

add ability to get last order.

ECWID-148789 OE2: Choose customer from existing customers

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/order/result/FetchedOrder.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NonUpdatablePropertyRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedOrderRules.kt

Ticket: [ECWID-159429](https://track.ecwid.com/youtrack/issue/ECWID-159429)

ECWID-159429 OE2: add delivery time slot to ecwid-java-api-client

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/category/request/CategoriesSearchRequest.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/CartsTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/OrdersTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/util/OrderUtils.kt

ECWID-157318 Negative promo targets - filter categories for exclusion list - apiclient

---

src/test/kotlin/com/ecwid/apiclient/v3/entity/BaseEntityTest.kt

- increasing delay for more processDelay calls

fixing tests before ECWID-157318 Negative promo targets - filter categories for exclusion list - apiclient

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/ReportType.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/BrandsTest.kt

ECWID-164575 New IS: Reports API — Contact widget

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/ReportType.kt

- added new reportType siteGroupActivity

ECWID-170718 New IS: New endpoint for aggregated statistics reports

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/ReportType.kt

- added new reportType siteUniqueNewVisitorsByGroup

ECWID-173015 New IS: Transform data on referer sources for weekly email

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/report/result/FetchedReportResponse.kt

Related PR in ecwid https://github.com/Ecwid/ecwid/pull/10601

ECWID-170952 - add cartOrigin param to report responses
