src/main/kotlin/com/ecwid/apiclient/v3/dto/coupon/request/CouponSearchRequest.kt
src/test/kotlin/com/ecwid/apiclient/v3/CouponsTest.kt

CouponSearchRequest get SetOf 'DiscountCouponType' as the discountType parameter because the client should form a string.

CouponSearchRequest get SetOf 'DiscountCouponType' v2

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/order/result/FetchedOrder.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NonUpdatablePropertyRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NullablePropertyRules.kt

- added 'id' field to FetchedOrder.OrderItemTax
- updated property rules

ECWID-88970 API: add tax ID to the Get order method

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/UpdatedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NullablePropertyRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedProductRules.kt

тикет https://track.ecwid.com/youtrack/issue/ECWID-99676

ECWID-99676 Delivery timeframes: new import/export

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedStoreProfile.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/profile/enums/ProductFilterType.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/profile/request/UpdatedStoreProfile.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/profile/result/FetchedStoreProfile.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/BaseEntityTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/StoreProfileTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NonUpdatablePropertyRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NonnullPropertyRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedStoreProfileRules.kt

Add ability to change productFiltersSettings in /api/v3/profile PUT endpoint; add ability to get productFiltersSettings.filterSections value in /api/v3/profile GET endpoint

Improvements for store profile's productFiltersSettings field

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/UpdatedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt

Make properties 'name' and 'nameTranslated' accessible without having to cast to the exact subtype of the option

Simplify access to properties in FetchedProduct.ProductOption and UpdatedProduct.ProductOption

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/UpdatedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NullablePropertyRules.kt

Make properties 'required', 'choices' and 'defaultChoice' in FetchedProduct.ProductOption and UpdatedProduct.ProductOption easier to access.
Note: defaultChoice was absent in CheckboxOption class, but to avoid making hierarchy more complex I decided to add it to the CheckboxOption with value null by default. It should not affect requests because server discards it as irrelevant

Common properties in sealed classes

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedCombination.kt
src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedOrder.kt
src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedStoreProfile.kt

Makes it easier to generalize functions used to generate/merge embedded fields

Make all toUpdate() methods public

---

src/test/kotlin/com/ecwid/apiclient/v3/entity/CategoriesTest.kt

If there are translations of other fields, the server now returns a map with empty values instead of null in fields seoTitleTranslated and seoTitleTranslated

Fix equality check to comply with changes in server's response

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/common/FetchedAttributeValue.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/common/UpdatedAttributeValue.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/custom/CustomAppRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/UpdatedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/variation/request/UpdatedVariation.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/variation/result/FetchedVariation.kt

Link together 'AttributeValue' classes which are declared in multiple classes to simplify processing of similar fields

Generalize nested classes

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/ComparePeriod.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/FirstDayOfWeek.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/ReportType.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/TimeScaleValue.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/report/request/ReportRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/report/result/FetchedReportResponse.kt

Енамы в ответах для Reports API неправильно парсятся, gson не может найти подходящего значения и всегда ставит null.

Fix deserialization of enums

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedOrder.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/order/request/UpdatedOrder.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/CartsTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/OrdersTest.kt

Added options files field to UpdatedOrder

ECWID-126818 OE2: Edit Items Options - file disappears from order after editing the item options.

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedCombination.kt
src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/UpdatedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/variation/request/UpdatedVariation.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/variation/result/FetchedVariation.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NullablePropertyRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedProductRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedVariationRules.kt

Ecwid 131152

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedCategory.kt
src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/category/request/UpdatedCategory.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/category/result/FetchedCategory.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/common/Alt.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/UpdatedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/subscriptions/request/SubscriptionsSearchRequest.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedCategoryRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedProductRules.kt

In Ecwid 116234, in order to use alt property in category, the alt needs to be added in the FetchedCategory class. Further more, since the product contains the same alt property for image and later variation, create a new FetchedAlt class and related converting logic for it to be reused.

Ecwid 116234 api client change

---

build.gradle.kts
src/main/kotlin/com/ecwid/apiclient/v3/dto/subscriptions/request/SubscriptionsSearchRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/metric/RequestRetrySleepMetric.kt
src/main/kotlin/com/ecwid/apiclient/v3/metric/RequestSizeMetric.kt
src/main/kotlin/com/ecwid/apiclient/v3/metric/RequestTimeMetric.kt
src/main/kotlin/com/ecwid/apiclient/v3/metric/ResponseSizeMetric.kt

This pull request primarily focuses on two areas of the codebase: the `SubscriptionsSearchRequest` data class and the metrics-related files in the `com.ecwid.apiclient.v3.metric` package. The changes in the `SubscriptionsSearchRequest` data class simplify the code by always setting the `offset` and `limit` parameters. The metrics-related files have been updated to use the `io.prometheus.metrics.core.metrics` package instead of the `io.prometheus.client` package, and several methods and parameters have been renamed or added to align with the new package's conventions.
Changes to `SubscriptionsSearchRequest` data class:
* [`src/main/kotlin/com/ecwid/apiclient/v3/dto/subscriptions/request/SubscriptionsSearchRequest.kt`](diffhunk://#diff-76ff2102c9ffea0bbec16b3e40301d8fc9c10c4d8c927f263b95642f …

Update prometheus lib to 1.1

---

src/test/kotlin/com/ecwid/apiclient/v3/entity/CustomersTest.kt

added customerName to order creation request in com.ecwid.apiclient.v3.entity.CustomersTest.testSearchFields

ECWID-139883 java-api-library: CustomersTest testSearchFields failed

---

src/main/kotlin/com/ecwid/apiclient/v3/dto/common/AsyncPictureData.kt

This pr is to add the additional alt property in api client to support public api change
Based on the [ticket](https://track.ecwid.com/youtrack/issue/ECWID-116277/Implement-alt-text-support-for-all-image-API) description, we need the following implementations:
Add `alt` property in `AsyncPictureData` dto.
Ticket: [ECWID-116277](https://track.ecwid.com/youtrack/issue/ECWID-116277)

ECWID-116277 Implement alt-text support for all image API

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedOrder.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/order/request/UpdatedOrder.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/order/result/FetchedOrder.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/CartsTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/OrdersTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedOrderRules.kt

added customerFiscalCode to FetchedOrder and UpdatedOrder

ECWID-135200 Recurring subscription orders are created without Tax ID although it's presented in the initial order

---

src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/report/enums/ReportType.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/report/result/FetchedReportResponse.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/NullablePropertyRules.kt

- added AdditionalCategoryData

ECWID-140946 New Reports: internal API for topOfCategoriesByOrders report

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/request/UpdatedProduct.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedProductRules.kt

Ticket: [ECWID-138159](https://track.ecwid.com/youtrack/issue/ECWID-138159)

ECWID-138159 Custom URL slugs for catalog pages: Product and categories export/import in CSV: add 'customSlug' field

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedOrder.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/order/request/UpdatedOrder.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/order/result/FetchedOrder.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/CartsTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/entity/OrdersTest.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedOrderRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/util/OrderUtils.kt

Ticket: [ECWID-153267](https://track.ecwid.com/youtrack/issue/ECWID-153267)

ECWID-153267 REST API: the 'lang' parameter in GET responses to /orders endpoint is not returned

---

.github/workflows/pull-request.yml
.github/workflows/push-to-master.yml

Last PR's Actions failed due to use of retired CodeQL Actions. With this PR I'm updating them 
https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/

Update deprecated github actions

---

src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedOrder.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/cart/request/OrderForCalculate.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/order/request/UpdatedOrder.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/order/result/FetchedOrder.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedOrderRules.kt
src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/OrderForCalculateRules.kt

Tiket: [ECWID-163221 New Order Editor: Tax is automatically reset to a standard rate if a product was deleted from catalog](https://track.ecwid.com/youtrack/issue/ECWID-163221/New-Order-Editor-Tax-is-automatically-reset-to-a-standard-rate-if-a-product-was-deleted-from-catalog)

ECWID-163221 New Order Editor: Tax is automatically reset to a standard rate if a product was deleted from catalog

---

src/main/kotlin/com/ecwid/apiclient/v3/ApiClient.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/images/request/ImagesMainColorsRequest.kt
src/main/kotlin/com/ecwid/apiclient/v3/dto/images/result/FetchedImagesMainColorsResult.kt
src/main/kotlin/com/ecwid/apiclient/v3/impl/ImagesApiClientImpl.kt

For the ticket: [ECWID-165825](https://track.ecwid.com/youtrack/issue/ECWID-165825) Add new endpoint to products service to be able to determine main colors of an image

Add images/main-colors endpoint
